site_name: Finanical Strategy
extra_css:
  - stylesheets/extra.css
theme:
   name: material
extra:
  generator: false
copyright: Copyright &copy; John Wheal
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
