site_name: Finanical Strategy
extra_css:
  - stylesheets/extra.css
theme:
   name: material
   icon:
     logo: fontawesome/solid/scale-unbalanced
extra:
  generator: false
copyright: Copyright &copy; John Wheal
nav:
  - 'index.md'
  - 'savings.md'
  - 'borrowing.md'
  - 'day-to-day.md'
  - 'budgeting.md'
  - 'emergency.md'
  - 'charity.md'
  - 'gambling.md'
  - 'tax.md'
  - 'insurance.md'
  - 'environmental.md'
  - 'energy.md'
  - 'analysis.md'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
