site_name: Finanical Strategy
extra_css:
  - stylesheets/extra.css
theme:
   name: material
extra:
  generator: false
copyright: Copyright &copy; John Wheal
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - 'index.md'
  - 'analysis.md'
  - 'savings.md'
  - 'borrowing.md'
  - 'day-to-day.md'
  - 'pots.md'
  - 'energy.md'
  - 'charity.md'
  - 'tax.md'
  - 'insurance.md'
  - 'environmental.md'
  - 'emergency.md'
